{% set name = "pcpp" %}
{% set version = "1.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5af9fbce55f136d7931ae915fae03c34030a3b36c496e72d9636cedc8e2543a1

build:
  noarch: python
  entry_points:
    - pcpp = pcpp:main
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - pcpp
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/ned14/pcpp
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A C99 preprocessor written in pure Python
  description: |
    A pure universal Python C (pre-)preprocessor implementation very useful
    for pre-preprocessing header only C++ libraries into single file includes and
    other such build or packaging stage malarky.
  doc_url: https://ned14.github.io/pcpp/
  dev_url: https://github.com/ned14/pcpp

extra:
  recipe-maintainers:
    - matthiasdiener
